services:
  oltp:
    image: postgres:15
    environment:
      POSTGRES_DB: "fund_oltp"
      POSTGRES_USER: "oltp_admin"
      POSTGRES_PASSWORD: "oltp_admin"
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fund_oltp"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  dw: 
    image: postgres:15
    environment:
      POSTGRES_DB: "fund_dw"
      POSTGRES_USER: "dw_admin"
      POSTGRES_PASSWORD: "dw_admin"
    ports: 
      - 54321:5432
    volumes:
      - ./import/csv:/import/csv
      - ./import/xml:/import/xml

  generator:
    build:
      context: .
      dockerfile: ./generator/Dockerfile
      args:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./import/csv/raw:/home/generator/csv
      - ./import/xml/raw:/home/generator/xml
    command: ["python", "generate.py"]
    depends_on:
      oltp:
        condition: service_healthy