services:
  oltp:
    image: postgres:15
    environment:
      POSTGRES_DB: "sales_oltp"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "sales_oltp"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  generator:
    build:
      context: .
      dockerfile: ./generator/Dockerfile
      args:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./import/csv/raw:/home/generator/csv
      - ./import/xml/raw:/home/generator/xml
    command: ["python", "generate.py"]
    depends_on:
      oltp:
        condition: service_healthy