name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment file
        run: |
          cp .env.example .env || echo "POSTGRES_USER=postgres\nPOSTGRES_PASSWORD=postgres" > .env

      - name: Build containers
        run: docker compose build

      - name: Run containers
        run: docker compose up  

      - name: Wait and test containers
        run: |
          sleep 10
          docker compose ps
          docker compose logs

      - name: Tear down
        if: always()
        run: docker compose down
